* Aaron Rebmann

--------------

#+BEGIN_QUOTE
  Specialties: C++, Python, Linux, Operations Research\\
  Doctor in Computer Science and Mathematics
#+END_QUOTE

--------------

** Corporate Experience

-  Since 2013 :: /Data Scientist for
   [[https://www.airconomy.com/][Airconomy]]/ (Frankfurt am Main,
   Germany).

   Data mining on various sources to forecast passenger demands over
   airline networks.

-  2009-2012 :: /PhD in Operations Research with
   [[http://www.amadeus.com/amadeus/amadeus.html][Amadeus]]/ (Sophia
   Antipolis, France).

   Researched how to assign aircraft on an airline network in the most
   efficient way. I authored several projects, including a C++ solver, a
   Python suite of 20+ command line tools, and Hadoop data mining
   scripts. I also worked as a teaching assistant at the university,
   further improving my communication and public speaking skills.

-  2008 (3 months) :: /Internship at
   [[http://www.riotintoalcan.com/][Rio Tinto Alcan]]/ (Clermont
   Ferrand, France).

   Co-authored a C++ library for optimizing the revenue of a metal
   factory. This work was published in the corporate journal of the
   company.

-  2007 (3 months) :: /Internship at
   [[http://www3.gehealthcare.com/en/Global_Gateway][GE Healthcare]]/
   (Paris, France).

   Elaborated an UML spec for the refactoring of 20.000 lines of C++.

** Selected Open Source Contributions

-  Python :: Contributor to
   [[http://code.google.com/p/pulp-or/][pulp-or]], a linear programming
   Python library. Author of small tools, like
   [[https://github.com/chmduquesne/michel][michel]], a command line
   program providing bidirectionnal synchronization of google tasks with
   text files.
-  C++ :: Author of
   [[http://yaposib.readthedocs.org/en/latest/index.html][yaposib]], a
   Python binding to COIN-OSI that is now supported by
   [[http://code.google.com/p/pulp-or/][pulp-or]].
-  C :: Author of
   [[https://code.google.com/p/lazylpsolverlibs/][lazylpsolverlibs]], a
   set of proxy libraries targeting cplex, gurobi and xpress. I also
   started writing
   [[https://github.com/chmduquesne/sharebox-fs][sharebox]], a
   distributed FUSE file system based on git.
-  Java :: Author of
   [[http://code.google.com/p/talkmyphone/][talkmyphone]], an android
   application allowing phone control via gtalk. It had 10.000+
   downloads, and was forked 50 times. It was then successfully handed
   over to [[http://code.google.com/p/gtalksms/][other developers]].
-  Misc :: Lua, Ada, Bash, Makefile, m4, autotools, cmake... See my
   [[http://resume.github.com/?chmduquesne][github résumé]]. My
   [[http://meta.ohloh.net/kudos/][kudorank]] on ohloh is 9, among the
   top 2% of opensource developers.
-  Linux :: My daily operating system: I [[http://blog.chmd.fr][blog]]
   about it sometimes.

** Education

-  2009-2012 :: /PhD in Mathematics and Computer Science at G-SCOP
   Laboratory/ (Grenoble, France).

   Title: Integration of Fleet Deployment and of Passenger Service in
   Airline Schedule Management. Done at Amadeus, in the Operation
   Research team led by [[http://www.linkedin.com/in/semigabteni][Semi
   Gabteni]]. Advisors: [[http://www.g-scop.inpg.fr/~naddefd/][Denis
   Naddef]],
   [[http://www.g-scop.inpg.fr/~brianto/index.php?page=1][Olivier
   Briant]]. Defended in January 2013.

-  2005-2009 :: /MS in Computer Science in ENSIMAG/ (Grenoble, France).

   Top French school of Applied Mathematics and Computer Science with
   highly selective recruitment.

-  2002-2005 :: /Preparatory classes in Lycée Thiers/ (Marseille,
   France).

   Mathematics and Physics courses before a national competitive
   examination to Grandes Écoles.

** Activities and interests

-  Hobbies :: I like travelling. I backpacked in 13 countries in Eastern
   Europe and South East Asia.
-  Sports :: Running, Cycling, Hiking. I also played rugby union for 7
   years.
-  Activities :: I was the president of the
   [[http://www.grandcercle.org][grand cercle]], one of the largest
   French campus student associations (5.000 members) during university.

--------------

#+BEGIN_QUOTE
  [[mailto:chmd@chmd.fr][chmd@chmd.fr]] • +336 84 14 26 82 • 28 years
  old\\
  275, chemin du Petit Castel - 13100 Aix en Provence, FRANCE
#+END_QUOTE
